In [2]:
import pandas as pd
import numpy as np

In [3]:
h_data=pd.read_csv("heart data.csv")

In [4]:
h_data.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No

In [5]:
h_data.describe()

                 BMI  PhysicalHealth   MentalHealth      SleepTime
count  319789.000000   319778.000000  319781.000000  319576.000000
mean       28.325348        3.371605       3.898384       7.096922
std         6.356134        7.950662       7.955291       1.436165
min        12.020000        0.000000       0.000000       1.000000
25%        24.030000        0.000000       0.000000       6.000000
50%        27.340000        0.000000       0.000000       7.000000
75%        31.420000        2.000000       3.000000       8.000000
max        94.850000       30.000000      30.000000      24.000000

In [7]:
h_data.describe(include='object')

,HeartDisease,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,Asthma,KidneyDisease,SkinCancer
count,319795,319721,319680,319774,319762,319482,319751,319756,319762,319779,319302,319795,319778,319795
unique,2,2,2,2,2,2,13,6,4,2,5,2,2,2
top,No,No,No,No,No,Female,65-69,White,No,Yes,Very good,No,No,No
freq,292422,187843,297908,307706,275363,167591,34143,245189,269626,247946,113657,276923,308001,289976

In [8]:
h_data.isna().sum()

HeartDisease          0
BMI                   6
Smoking              74
AlcoholDrinking     115
Stroke               21
PhysicalHealth       17
MentalHealth         14
DiffWalking          33
Sex                 313
AgeCategory          44
Race                 39
Diabetic             33
PhysicalActivity     16
GenHealth           493
SleepTime           219
Asthma                0
KidneyDisease        17
SkinCancer            0
dtype: int64

In [10]:
h_data['BMI'].fillna(h_data['BMI'].median(),inplace=True)
h_data['PhysicalHealth'].fillna(h_data['PhysicalHealth'].median(),inplace=True)
h_data['MentalHealth'].fillna(h_data['MentalHealth'].median(),inplace=True)
h_data['SleepTime'].fillna(h_data['SleepTime'].median(),inplace=True)
h_data['Smoking'].fillna(h_data['Smoking'].mode()[0],inplace=True)
h_data['AlcoholDrinking'].fillna(h_data['AlcoholDrinking'].mode()[0],inplace=True)
h_data['Stroke'].fillna(h_data['Stroke'].mode()[0],inplace=True)
h_data['DiffWalking'].fillna(h_data['DiffWalking'].mode()[0],inplace=True)
h_data['Sex'].fillna(h_data['Sex'].mode()[0],inplace=True)
h_data['AgeCategory'].fillna(h_data['AgeCategory'].mode()[0],inplace=True)
h_data['Race'].fillna(h_data['Race'].mode()[0],inplace=True)
h_data['Diabetic'].fillna(h_data['Diabetic'].mode()[0],inplace=True)
h_data['PhysicalActivity'].fillna(h_data['PhysicalActivity'].mode()[0],inplace=True)
h_data['GenHealth'].fillna(h_data['GenHealth'].mode()[0],inplace=True)
h_data['KidneyDisease'].fillna(h_data['KidneyDisease'].mode()[0],inplace=True)

In [11]:
h_data.isna().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:

plt.figure(figsize=(8, 6))
sns.countplot(x='HeartDisease', data_data)
plt.title('Distribution of Heart Disease')
plt.xlabel('Heart Disease')
plt.ylabel('Count')
plt.show()

NameError: name 'heart_data' is not defined